### ISSUE TITLE
Do you have a comparison of how this performs compared to spacy-stanza?

### ISSUE THREAD

**Issue by jzohrab** [pablodms/spacy-spanish-lemmatizer#12]
Hi there, thank you for this fun-looking project!  I'm looking for lemmatizing options for personal use.

I briefly browsed the code here.  Also from a stackoverflow post ([link)(https://stackoverflow.com/questions/60534999/how-to-solve-spanish-lemmatization-problems-with-spacy)), I found https://github.com/explosion/spacy-stanza, which also looks good and has a pre-trained model.

Do you know how your project compares with that, both in terms of speed and accuracy?  Cheers and best wishes, jz

**Comment by pablodms** [comment]
Hi @jzohrab,

I'm glad that you took an interest in this project, it's been some time since I started it. In summary, the code takes advantage of the great database that Wikimedia has about Spanish word derivations by parsing its semi-structured data and adapting it to Spacy.

When I tested it back in 2020, as a Spanish native, I found it very accurate (especially when compared with Spacy's built-in lemmatizer) but also slow, as it takes up a lot of space to store the derivations and lemmatization is just a search in the generated files. It uses a strategy based on memorization rather than training and inference, so I wouldn't expect it to be as efficient.

You can give it a try and if you find it lacking I encourage you to improve it and even create your own version.

Best regards

**Comment by jzohrab** [comment]
Yep memoization makes some sense for this approach, it's a tradeoff but a good one.  Sharding the source files could make it much faster, I put a note in the other issue for others to take on if they want.

Gracias por tu trabajo.  No estoy seguro so lo voy a usar o no, pero es una buena opción.  Saludos!
