### ISSUE TITLE
Error [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component

### ISSUE THREAD

**Issue by ivanierruk** [pablodms/spacy-spanish-lemmatizer#9]
I'm using linux manjaro OS, a venv with python 3.8 and 3.9, i was able to use the spanish lemmatizer following the instructions, but recently i'm having this error which indicates something with the factory_name not being correct:

![Captura de pantalla_2021-02-23_12-18-05](https://user-images.githubusercontent.com/65654114/108889063-8979af00-75d1-11eb-8467-18e9a047b3c3.png)

I don't understand what the problem is, since it worked and i have not updated or moved anything, here's the code: 

![tt](https://user-images.githubusercontent.com/65654114/108889444-00af4300-75d2-11eb-9a61-23933a2db247.png)

i hope you can help me with the issue, thank you very much, best regards!!

**Comment by pablodms** [comment]
Hello @ivanierruk,

Sorry for my late reply,

The problem is related to the release of spaCy 3.0. They changed the `add_pipe` signature so the example code did not work. 

I have addressed this issue so the component is now compatible with spaCy 3.0 and I have also updated the example code. You should download or install the latest version of `spacy_spanish_lemmatizer` via git or pip in order to solve the error.

Thank you very much for spotting this compatibility issue. Let me know if the error persists.

Best regards
